info:
  component: Simple Zuul Proxy Server

cloud:
  conablefig:
    failFast: true
    discovery:
      end: true

zuul:
  ignoredServices: "*"
  routes:
    UbuntuArchive:
      url: http://us.ubuntu.archive.com

server:
  port: 8080

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
    info.tcb: DEBUG