spring:
  application:
    name: charisma
  boot:
    admin:
      client:
        prefer-ip: true
        enabled: true
        name: charisma
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
management:
  security:
    enabled: false