spring:
  application:
    name: pamyu
#  cloud:
#    config:
#      enabled: false
info:
  stage: test
endpoints:
  sensitive: false
  docs:
    curies:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    eureka-service-url-poll-interval-seconds: 5
  instance:
    prefer-ip-address: true
    appname: ${spring.application.name}
management:
  security:
    enabled: false
