server:
  context-path: /mamamoo
  port: 8888
spring:
  cloud:
    config:
      server:
        native:
          search-locations: config/
          fail-on-error: true
        git:
          uri: config/
          basedir: config/
eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    eureka-server-u-r-l-context: /charisma
    service-url: http://localhost:8147
