spring:
  application:
    name: charisma
  boot:
    admin:
      client:
        prefer-ip: true
        enabled: true
        name: charisma
server:
  context-path: /charisma
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    eureka-server-u-r-l-context: /charisma
  instance:
    appname: ${spring.application.name}
    home-page-url-path: ${server.context-path}
    status-page-url-path: ${server.context-path}/info
    health-check-url-path: ${server.context-path}/health
  server:
    renewal-threshold-update-interval-ms: 1000
    renewal-percent-threshold: 1.00
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
management:
  security:
    enabled: false

